//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNI
{
    using System;
    using System.Collections.Generic;
    
    public partial class course
    {
        public int course_Id { get; set; }
        public string title { get; set; }
        public string dept_name { get; set; }
        public string credits { get; set; }
    
        public virtual section section { get; set; }
    }
}
